---
grails:
    profile: web
    codegen:
        defaultPackage: au.org.ala.specieslist
    config:
        locations:
            - file:/data/specieslist-webapp/config/specieslist-webapp-config.properties
            - file:/data/specieslist-webapp/config/specieslist-webapp-config.yml
            - file:/data/specieslist-webapp/config/specieslist-webapp-config.groovy
    gorm:
        # Whether to autowire entities.
        # Disabled by default for performance reasons.
        autowire: false
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
    spring:
        transactionManagement:
            proxies: false
    cors:
        enabled: true
        allowCredentials: true
        allowedMethods:
            - '*'
        allowedHeaders:
            - '*'
        allowedOrigins:
            - '*'
        mappings:
            /ws/**: inherit
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    jmx:
        unique-names: true
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
    devtools:
        restart:
            additional-exclude:
                - '*.gsp'
                - '**/*.gsp'
                - '*.gson'
                - '**/*.gson'
                - 'logback.groovy'
                - '*.properties'

management:
    endpoints:
        enabled-by-default: false

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
                - text/html
                - application/xhtml+xml
            js: text/javascript
            json:
                - application/json
                - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
                - application/hal+json
                - application/hal+xml
            xml:
                - text/xml
                - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
        upload:
            maxFileSize: 31457280
            maxRequestSize: 31457280
    converters:
        encoding: UTF-8
    views:
        default:
            codec: none
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlet: html
                taglib: none
                staticparts: none
management:
    endpoints:
        jmx:
            unique-names: true

---

hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory

dataSource:
    pooled: true
    jmxExport: true
    driverClassName: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL8Dialect
    username: root
    password: 'password'

environments:
    development:
        grails:
            serverURL: "http://dev.ala.org.au:8080"
        dataSource:
            dbCreate: none
            url: jdbc:mysql://localhost/specieslist?autoReconnect=true&connectTimeout=0&useUnicode=true&characterEncoding=UTF-8
            username: specieslist
            password: "specieslist"
        security:
            cas:
                appServerName: "http://dev.ala.org.au"
    test:
        grails:
            serverURL: "https://lists-test.ala.org.au"
        dataSource:
            dialect: org.hibernate.dialect.H2Dialect
            pooled: true
            jmxExport: true
            driverClassName: org.h2.Driver
            username: 'specieslist'
            password: 'specieslist'
            dbCreate: create-drop
            url: jdbc:h2:mem:specieslist;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
        security:
            cas:
                appServerName: "https://lists-test.ala.org.au"
    production:
        grails:
            serverURL: "https://lists.ala.org.au"
        dataSource:
            dbCreate: update
            url: jdbc:mysql://localhost/specieslist?autoReconnect=true&connectTimeout=0&useUnicode=true&characterEncoding=UTF-8
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
        security:
            cas:
                appServerName: "https://lists.ala.org.au"

---
headerAndFooter:
    baseURL: "https://www.ala.org.au/commonui-bs3-2019"
    version: "2"

skin:
    layout: "main"
    fluidLayout: true
    orgNameLong: "Atlas of Living Australia"
    orgNameShort: "ALA"

publicview:
    hidePrivateLists: false

outboundhttp:
    useragent: 'species-lists'
    timeout: 8000

namematching:
    serviceURL: https://namematching.legacy.nbnatlas.org
    dataCacheConfig:
        enableJmx: true
        entryCapacity: 20000
        eternal: true
        keepDataAfterExpired: false
        permitNullValues: false
        suppressExceptions: true

security:
    cas:
        enabled: false
    oidc:
        enabled: true
        discoveryUri: https://auth-dev.ala.org.au/cas/oidc/.well-known
        scope: openid profile email ala roles
#        allowUnsignedIdTokens: true
    jwt:
        enabled: true
        discoveryUri: https://auth-dev.ala.org.au/cas/oidc/.well-known
        fallbackToLegacyBehaviour: true

webservice:
    jwt: true
    jwt-scopes: "openid users/read"

userDetails:
    url: https://auth-dev.ala.org.au/userdetails

speciesNameColumns: 'scientificname,scientific,sciname,sname,latinname,latin,taxon,taxonname,taxonomic name'
commonNameColumns: 'commonname,common,vernacular,vernacularname'
ambiguousNameColumns: 'name'
kingdomColumns: 'kingdom,regnum'
phylumColumns: 'phylum,divisio,division'
classColumns: 'class,classis,clazz,class_,classs'
orderColumns: 'order,ordo'
familyColumns: 'family,familia'
genusColumns: 'genus,genericEpithet,generic epithet'
rankColumns: 'taxonrank,rank,taxon rank,taxonomicrank,taxonomic rank,linnaean rank'