---
grails:
    profile: web
    codegen:
        defaultPackage: uk.org.nbn.specieslist
    spring:
        transactionManagement:
            proxies: false
    gorm:
        # Whether to autowire entities.
        # Disabled by default for performance reasons.
        autowire: false
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
    cors:
        enabled: true
        mappings:
            /ws/**: inherit

info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
---
security:
    filterOrder: 0
    basic:
        enabled: true
        authorizeMode: role
        realm: species list
        path:
        - /status/**
    bootadmin:
        url: ''

spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
    boot:
        admin:
            client:
                enabled: true
                name: specieslist
                service-base-url: ${grails.serverURL} # app base URL with no context path#
                metadata:
                    user:
                        name: ${security.user.name}
                        password: ${security.user.password}
            url: ${security.bootadmin.url}
            username:  ${security.bootadmin.user.name}
            password: ${security.bootadmin.user.password}

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: true
    sensitive: true
    jmx:
        enabled: true
        unique-names: true
    cors:
        allow-credentials: true
        allowed-methods:
            - GET
            - POST
            - DELETE
            - PUT
        allowed-headers: "*"
        allowed-origins:
            - ${spring.boot.admin.url}

management:
    context-path: /status # moves actuator endpoints from eg /appContext/health to /appContext/status/health so they don't clash with any existing URL mappings
    security:
        enabled: true
        roles: ACTUATOR

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
                - text/html
                - application/xhtml+xml
            js: text/javascript
            json:
                - application/json
                - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
                - application/hal+json
                - application/hal+xml
            xml:
                - text/xml
                - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
        upload:
            maxFileSize: 31457280
            maxRequestSize: 31457280
    converters:
        encoding: UTF-8
    views:
        default:
            codec: none
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
